var appConstants = {
    FETCH_TRAINERS: "FETCH_TRAINERS",
    FETCH_TRAINER: "FETCH_TRAINER",
    ADD_TRAINER: "ADD_TRAINER",

    FETCH_POKEMON: "FETCH_POKEMON",
    FETCH_POKEMON_FOR_TRAINER: "FETCH_POKEMON_FOR_TRAINER",
    ADD_POKEMON: "ADD_POKEMON"
};

module.exports = appConstants;
